development:
  adapter: postgresql
  encoding: utf8
  database: houston_testing_report_development
  host: localhost
  prepared_statements: false

test:
  adapter: postgresql
  encoding: utf8
  database: houston_testing_report_test
  host: localhost
  prepared_statements: false
